language: go

os:
  - linux
  - osx

go:
  - '1.7'
  - '1.8'

services:
  - docker
env:
  global:
    - CONTROLLER_IMAGE_NAME=bitnami/kubeless-controller
    - CONTROLLER_IMAGE=${CONTROLLER_IMAGE_NAME}:${TRAVIS_TAG:-build-$TRAVIS_BUILD_ID}
    - CGO_ENABLED=0

before_install:
  - set -e

install:
  - go get github.com/mitchellh/gox github.com/golang/lint/golint
  - >-
    wget -O $GOPATH/bin/kubecfg
    https://github.com/ksonnet/kubecfg/releases/download/v0.2.0/kubecfg-$(go env GOOS)-$(go env GOARCH)
  - chmod +x $GOPATH/bin/kubecfg
  - git clone --depth=1 https://github.com/ksonnet/ksonnet-lib.git
  - export KUBECFG_JPATH=$PWD/ksonnet-lib

script:
  - make test
  - make validation
  - make binary
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      make controller-image CONTROLLER_IMAGE=$CONTROLLER_IMAGE
    fi
  - make kubeless.yaml

after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == linux && \
          "$TRAVIS_BRANCH" == master && \
          "$TRAVIS_PULL_REQUEST" == false && \
          "$TRAVIS_GO_VERSION" == "1.8" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag $CONTROLLER_IMAGE ${CONTROLLER_IMAGE_NAME}:latest
      docker push ${CONTROLLER_IMAGE_NAME}:latest
    fi

before_deploy:
  - make binary-cross
  - for d in bundles/kubeless_*; do zip -r9 $d.zip $d/; done
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker push $CONTROLLER_IMAGE
      NEW_DIGEST=$(./script/find_digest.sh ${CONTROLLER_IMAGE_NAME} ${TRAVIS_TAG} | cut -d " " -f 2)
      OLD_DIGEST=$(cat kubeless.yaml | grep ${CONTROLLER_IMAGE_NAME} |  cut -d "@" -f 2)
      sed 's/'"$OLD_DIGEST"'/'"$NEW_DIGEST"'/g' kubeless.yaml > kubeless-${TRAVIS_TAG}.yaml
    fi

deploy:
  provider: releases
  api_key:
    secure: "ajLd8V/afkBM6a8RVaRQxui95Kpqx7jjPuZeO4D7re/wH1jODT/qswsCMXNG6nlq334nce0HoIW7zGVME1RaC8+nT/PIJG3I/k9oQg9AvUJqILzFNBaj2hg07DNzzDpQiNER8YTjMliAQhlUseTEYEAl1pfBSbZFWn6WV0SqFEji3ZhO5SdEMGmC6RzBZ21/3sBr+h6c6HG5Wb+qXr+Im83/+/wke3M8qKsSgsalJ0fpbonubicq4AzprNIBl6QZi77LZiqQCnPSD1Sop92p8wu5LgJ6CLEK3tOpFTZcJ8FYSAhBp0ipZ4adNTwZgwcXFd9FcSm10whD3WM5pgzAhtq0TB9QVbOdLL6ppANgAlFuIITsToxlAohyt2GwJPXb3mppG/m/1hGyXiy3y1uURn2x7kRR20uBtRgkUqwlKdKUlD57I4f+681oVwxcKvEr07h4l7gg4EtbmbnQHzGSFXhZ4sF2z6iqBG0I6gaQT+hJPyQIrpryGWqQAQt9YZGF/AiUxndQrIaQ8AK4IemKRlFYkTqrB2GLQR1wlSSQejOoZ4157QfgCdNKk1NxqRWDJLPOHHAWTiU21msKBlhDkiga2xrouS849HK+6SyYUKall/Q0XxmCFEo5JsBppYhWrWGzToXuCK1p+AfGUlR3YeAm+wKg3ivELdb+qRGP9ro="
  file_glob: true
  file:
    - kubeless-${TRAVIS_TAG}.yaml
    - bundles/kubeless_*.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: kubeless/kubeless
    go: 1.8
    os: linux
    condition: $CGO_ENABLED = 0
